---
resources:
- name: jmye-resource-git
  type: git
  source: 
    uri: https://github.com/johnpmyers/concourse-jmyers.git
    branch: master
- name: version
  type: semver
  source:
    driver: s3
    initial_version: 0.0.1
    access-key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))
    bucket: ((version_aws_bucket))
    region_name: us-east-1
    key: version

jobs:
- name: jmye-list-files
  plan:
  - get: jmye-resource-git
    trigger: true
  - task: task-list-files
    file: jmye-resource-git/tasks/list-files/task-list-files.yml
- name: job-bump-artifact-version
  plan:
  - get: jmye-resource-git
    trigger: true
    passed: [ jmye-list-files ]
  - get: version
  - task: task-display-version
    file: jmye-resource-git/tasks/display-version/task-display-version.yml
  - put: version
    params: {bump: patch}
